### ISSUE TITLE
New npm version

### ISSUE THREAD

**Issue by mgrisole** [Duder-onomy/svelte-focus-trap#2]
Hi @Duder-onomy, would it be possible to publish a new version of the package with the declaration file please ? =)

**Comment by Duder-onomy** [comment]
On it. My bad.  Just published 1.2.0

I made this lib when I was experimenting with Svelte. I have not been able to convince anyone I work with to use Svelte yet. So I don't actually use this lib.  Would you want to take control of it?  I can transfer ownership to you, or add you, or just deprecate this one and you can take the `svelte-focus-trap` name. 
Let me know.

**Comment by mgrisole** [comment]
No worries, too bad your team didn't follow your advices =/

You can add me as a collaborator, I will gladly help keeping this package alive.
