### ISSUE TITLE
The requested module does not provide an export named 'default'

### ISSUE THREAD

**Issue by RomanistHere** [Duder-onomy/svelte-focus-trap#4]
![image](https://user-images.githubusercontent.com/49812531/133986464-83836fa0-d659-4263-a236-757b534a69c1.png)

The requested module '/node_modules/mousetrap/mousetrap.js?v=953dd794' does not provide an export named 'default'

![image](https://user-images.githubusercontent.com/49812531/133986625-266e7802-a267-4ac6-a0b0-b45286816fc9.png)

My info:

Windows 10,
SvelteKit
![image](https://user-images.githubusercontent.com/49812531/133986902-aa52b874-9e5e-4385-ac82-6afaa0bb53b1.png)

**Comment by RomanistHere** [comment]
Created PR: https://github.com/Duder-onomy/svelte-focus-trap/pull/5/files

**Comment by Duder-onomy** [comment]
Sorry about the late reply. 
Does your PR work for you? I am trying to test locally, but have not seen that specific issue you are referring to.

**Comment by Duder-onomy** [comment]
@RomanistHere I have a feeling this has to do with your bundler?

On a fresh install of svelte kit:

* `npm init svelte@next test-sveltekit`
* `cd test-sveltekit`
* `npm install`
* `npm install svelte-focus-trap`
* `npm run dev`

^ everything works as the lib exists right now. 

FWIW, I found a few other small issues which I will try to fix shortly. 

Can you let me know if anything else could be going on?  Using your PR works for me as well.. so maybe we should just merge it.

**Comment by RomanistHere** [comment]
I run the project with the old sveltekit version, after upgrading with `npm update` and reinstalling `svelte-focus-trap` everything seems to work as excepted. Thank you for help and for the module, it's cool and very useful!

So, if you want to support older versions of sveltekit, you can merge my PR, however I would probably not do it, since everything's working fine for the last versions. But we could keep the PR and point to this conversation in case upgrading SvelteKit version for someone would not be an option. You could merge it then.
