### ISSUE TITLE
Svelte resolve configuration warning.

### ISSUE THREAD

**Issue by olafurw** [Duder-onomy/svelte-focus-trap#7]
I was building my project and got this warning.

```
13:20:01 [vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.

svelte-focus-trap@1.2.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.
```

**Comment by Duder-onomy** [comment]
@olafurw I was able to put together a PR that *should* fix this issue. 

https://github.com/Duder-onomy/svelte-focus-trap/pull/9

I think this should solve things as it is now a `Sveltekit Library` and the Svelte version resolution should be fixed. 

If you wanted to give that PR a try I would appreciate it.  

I am going to merge it in a few days.

**Comment by olafurw** [comment]
Full rewrite, nice. I'll check it when it appears in my NPM, but I stopped getting a warning when `vite-plugin-svelte` fixed a normalization issue.

https://github.com/sveltejs/vite-plugin-svelte/issues/634
